"""added todolists

Revision ID: de4f7c3e41aa
Revises: 28b4d3cd458c
Create Date: 2020-03-28 10:47:06.396078

"""
import traceback

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4f7c3e41aa'
down_revision = '28b4d3cd458c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todolists', ['list_id'], ['id'])

    #über psql commands ausführen:
    #op.execute('INSERT INTO todolists (name) VALUES ("Uncategorized");')
    #op.execute('UPDATE todo SET list_id = 1 WHERE list_id IS NULL;')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
